module.exports = [
  {
    Name: "Gaurav",
    MobileNo: 919871324442,
    ScheduleTag: "Testing",
    WA: "",
    WW: "",
    SentReport: "",
    email: "tempMail@gmail.com",
  },
  {
    Name: "Dev",
    MobileNo: 919910513597,
    ScheduleTag: "Testing",
    WA: "",
    WW: "",
    SentReport: "",
    email: "tempMail@gmail.com",
  },
  {
    Name: "Chirag",
    MobileNo: 919870495565,
    ScheduleTag: "Testing",
    WA: "",
    WW: "",
    SentReport: "",
    email: "tempMail@gmail.com",
  },
  {
    Name: "Khyati",
    MobileNo: 919919944450,
    ScheduleTag: "Testing1",
    WA: "",
    WW: "",
    SentReport: "",
    email: "tempMail@gmail.com",
  },
  {
    Name: "AVISHKAR",
    MobileNo: 917517412238,
    ScheduleTag: "Testing1",
    WA: "",
    WW: "",
    SentReport: "",
    email: "tempMail@gmail.com",
  },
  {
    Name: "Veronica",
    MobileNo: 919657871559,
    ScheduleTag: "Testing1",
    WA: "",
    WW: "",
    SentReport: "",
    email: "tempMail@gmail.com",
  },
  {
    Name: "Leena",
    MobileNo: 918329037328,
    ScheduleTag: "Testing1",
    WA: "",
    WW: "",
    SentReport: "",
    email: "tempMail@gmail.com",
  },
];
